apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mlops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: samdataiken/frontend-service:dev
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          hostPath:
            path: /full/path/to/config  # change aussi ce chemin

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mlops-demo
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
