apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  namespace: mlops-demo
  labels:
    app: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
        - name: inference
          image: samdataiken/inference-service:dev
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: project-env
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            - name: params-volume
              mountPath: /app/config/params.yaml
              subPath: params.yaml
            - name: processed-data-volume
              mountPath: /app/data/processed
      volumes:
        - name: config-volume
          configMap:
            name: inference-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: params-volume
          configMap:
            name: inference-params
            items:
              - key: params.yaml
                path: params.yaml
        - name: processed-data-volume
          persistentVolumeClaim:
            claimName: processed-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: mlops-demo
spec:
  selector:
    app: inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32502
  type: NodePort
