apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: mlops-demo
spec:
  selector:
    app: inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
